dataset:
  name: Semantic3D
  batcher: DefaultBatcher
  batch_size: 1
  cache_dir: ./logs/cache_mysemantic3d/
  class_weights: [21302, 12073, 13106, 0, 5431, 5994, 3605, 8412, 4322, 2571, 15486, 1440, 17878]
  ignored_label_inds: []
  num_points: 111620
  test_result_folder: ./test
  num_classes: 13
  # use_cache: true
  val_files:
  - data
  steps_per_epoch_train:
  steps_per_epoch_valid:
model:
  name: MySemantic3D
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 5
  num_points: 111620
  num_classes: 13
  voxel_size: 0.02
  ignored_label_inds: []
  sub_sampling_ratio: [4, 4, 4, 4, 2]
  in_channels: 3
  dim_features: 3
  dim_output: [16, 64, 128, 256, 512]
  grid_size: 0.06
pipeline:
  name: SemanticSegmentation
  logs_dir: './logs'
  optimizer:
    lr: 0.001
  batch_size: 1
  main_log_dir: ./logs
  max_epoch: 500
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 2
  train_sum_dir: train_log
  val_batch_size: 2
  num_classes: 13
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
